In [5]:
import pandas as pd
data = pd.read_csv("/content/Dataset Clima.csv")
data

,id,Humidity,Wind_Speed_kmh,rumbo_viento_grados,visibilidad_km,presion_mbar,lluvia,descripcion,temperatura
0,0,0.92,11.27,130.0,8.05,1021.60,no,Cold,-0.56
1,1,0.73,20.93,330.0,16.10,1017.00,si,Warm,21.11
2,2,0.97,5.97,193.0,14.91,1013.99,si,Normal,16.60
3,3,0.82,3.22,300.0,16.10,1031.59,si,Cold,1.60
4,4,0.60,10.88,116.0,9.98,1020.88,si,Cold,2.19
...,...,...,...,...,...,...,...,...,...
9995,9995,0.95,10.24,20.0,4.01,1007.41,si,Normal,10.02
9996,9996,0.64,11.04,80.0,9.98,1031.33,si,Normal,8.63
9997,9997,0.93,11.04,269.0,14.91,1014.21,si,Normal,5.98
9998,9998,0.78,8.18,231.0,7.82,1005.02,si,Normal,9.79
9999,9999,0.79,14.25,131.0,10.26,1010.14,si,Normal,11.14

In [3]:
data.head()

,id,Humidity,Wind_Speed_kmh,rumbo_viento_grados,visibilidad_km,presion_mbar,lluvia,descripcion,temperatura
0,0,0.92,11.27,130.0,8.05,1021.60,no,Cold,-0.56
1,1,0.73,20.93,330.0,16.10,1017.00,si,Warm,21.11
2,2,0.97,5.97,193.0,14.91,1013.99,si,Normal,16.60
3,3,0.82,3.22,300.0,16.10,1031.59,si,Cold,1.60
4,4,0.60,10.88,116.0,9.98,1020.88,si,Cold,2.19

In [6]:
#cant de filas y columnas
data.shape

(10000, 9)

In [7]:
#tipo de dato
data.dtypes

id                       int64
Humidity               float64
Wind_Speed_kmh         float64
rumbo_viento_grados    float64
visibilidad_km         float64
presion_mbar           float64
lluvia                  object
descripcion             object
temperatura            float64
dtype: object

In [11]:
#para ver si los datos estan completos
data['descripcion'].isna()           #para ver si hay un Nan (casilla en blanco) - lista true/false
data['descripcion'].isna().sum()
data[data['descripcion'].isna()]  #registros donde faltan datos  -

,id,Humidity,Wind_Speed_kmh,rumbo_viento_grados,visibilidad_km,presion_mbar,lluvia,descripcion,temperatura
549,549,0.55,20.46,160.0,10.21,1020.71,si,NaN,8.91
1485,1485,0.56,16.04,33.0,10.35,1021.43,si,NaN,2.83
2224,2224,0.48,11.27,120.0,9.98,1011.10,si,NaN,16.11
3485,3485,0.45,13.78,341.0,16.10,1019.04,si,NaN,23.79
5382,5382,0.92,4.73,170.0,3.53,1006.13,no,NaN,-5.16
6582,6582,0.65,27.10,319.0,9.98,0.00,si,NaN,4.95
7815,7815,NaN,NaN,NaN,NaN,NaN,si,NaN,0.98
9614,9614,0.82,11.27,10.0,16.10,1019.90,si,NaN,0.56

In [14]:
data.isnull()    #mustra en toda la columna los datos Nan
data.isnull().sum()

id                     0
Humidity               5
Wind_Speed_kmh         5
rumbo_viento_grados    5
visibilidad_km         5
presion_mbar           9
lluvia                 1
descripcion            8
temperatura            0
dtype: int64

In [ ]:
del(data["id"])
data