In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/data_clima_numerico_limpia.csv")

In [6]:
data[['humedad', 'temperatura']].head(15)

    humedad  temperatura
0      0.92        -0.56
1      0.73        21.11
2      0.97        16.60
3      0.82         1.60
4      0.60         2.19
5      0.32        27.54
6      0.84        19.98
7      0.86        11.11
8      0.73         8.41
9      0.81         1.70
10     0.88        -2.22
11     0.60        21.90
12     0.87        17.11
13     0.73        17.77
14     0.39        24.95

In [7]:
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
from sklearn.model_selection import train_test_split 

X = data.drop(columns='humedad')
y = data['temperatura']

X_train, X_test, y_train, y_test = train_test_split(X,y,)

In [14]:
import numpy as np

In [18]:
#Importamos una regression lineal
from sklearn.linear_model import LinearRegression